# Generated by Django 5.2.1 on 2025-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallisting',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
