# Generated by Django 5.2.1 on 2025-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rentallisting_main_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
