# Generated by Django 5.2.1 on 2025-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraperequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforwardListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(unique=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('agent_phones', models.JSONField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RentalListing',
            new_name='MakaziListing',
        ),
    ]
