# Generated by Django 5.2.1 on 2025-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_beforwardlisting_rename_rentallisting_makazilisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforwardScrapeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='beforwardlisting',
            name='details',
        ),
        migrations.AlterField(
            model_name='beforwardlisting',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beforwardlisting',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beforwardlisting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
